# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Friends, Peace, & Sanctuary"
title_separator          : "-"
name                     : "Swarthmore College"
# url                      : # "https://mmistakes.github.io"
url                      : #""
baseurl                  : ""
languages                : ["en", "ar"]
exclude_from_localizations: ["assets","assets/js","assets/images","assets/css","assets/fonts"]

# Social Sharing
twitter:
  username               : "fpsbookarts"
facebook:
  username               : "fpsbookarts"
  app_id                 :
  publisher              :
instagram:
  username               : "fpsbookarts"

# Analytics
analytics:
  provider               : custom # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-58250963-5


# Site Author
author:
  name             : "Swarthmore College Libraries"
  facebook         :
  instagram        :
  twitter          :
  url              : "https://www.swarthmore.edu/libraries"

# Placeholders
placeholder:
  image: logo-placeholder.svg
  bio: >
    As part of FPS, members of the Iraq and Syrian refugee communities of Philadelphia have graciously contributed their valuable time, input and lent their experiences to the project.


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - "*.gempspec"
  - images_orig
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: nested # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-minimagick
  - jemoji
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# mini magick image processing
mini_magick:
  resize:
    source: assets/images
    destination: assets/images
    resize: "800x>"

jekyll-archives:
  enabled: ['tags','categories']
  layout: archive-taxonomy
  permalinks:
    tag: '/:name/'
    category: '/:name/'

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

# Prose settings
prose:
  rooturl: '_posts'
  media: 'assets/images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "title_ar"
        field:
          element: "text"
          label: "Event Title in Arabic"
          help: "For Exhibition Programming, Event Title in Arabic (optional)"
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          options:
            - name: "English"
              value: "en"
            - name: "Arabic"
              value: "ar"
      - name: "date"
        field:
          element: "text"
          help: Date of post affects in which order posts appear
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          placeholder: "choose categories"
          options:
            - name: "Public Events"
              value: "public events"
            - name: "Conversations"
              value: conversations
            - name: "Works"
              value: works
            - name: "Workshops"
              value: workshops
            - name: "Exhibitions"
              value: exhibitions
            - name: "Exhibition Programming"
              value: exhibition programming
            - name: "Swarthmore Exhibit"
              value: "exhibit:swarthmore"
            - name: "City Hall Exhibit"
              value: "exhibit:city hall"
            - name: "Twelve Gates Exhibit"
              value: "exhibit:twelve gates"
            - name: "Booklyn Exhibit"
              value: "exhibit:booklyn"
            - name: "Free Library Exhibit"
              value: "exhibit:free library"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "choose or add tags"
          alterable: true
          options:
            - name: "Amaal AlNajjar"
              value: "artist:Amaal AlNajjar"            
            - name: "Abir AlArnab"
              value: "artist:Abir AlArnab"
            - name: "Abdul Karim"
              value: "artist:Abdul Karim Awad"
            - name: "Ali Salman"
              value: "artist:Ali Salman"
            - name: "Asmaa Diab"
              value: "artist:Asmaa Diab"
            - name: "Courtney Bowles"
              value: "artist:Courtney Bowles"
            - name: "Erik Ruin"
              value: "artist:Erik Ruin"
            - name: "Fadaa Ali"
              value: "artist:Fadaa Ali"
            - name: "Fadia Lilmakhzoub"
              value: "artist:Fadia Lilmakhzoub"
            - name: "Fouad Sakhnini"
              value: "artist:Fouad Sakhnini"
            - name: "Islam Aly"
              value: "artist:Islam Aly"
            - name: "Layla Al Hussein"
              value: "artist:Layla Al Hussein"
            - name: "Mark Strandquist"
              value: "artist:Mark Strandquist"
            - name: "Marwa"
              value: "artist:Marwa"
            - name: "Maureen Cummins"
              value: "artist:Maureen Cummins"
            - name: "Mohamed"
              value: "artist:Mohamed"
            - name: "Osama Herkal"
              value: "artist:Osama Herkal"
            - name: "Raghad Samir"
              value: "artist:Raghad"
            - name: "Roula Al Jabi"
              value: "artist:Roula Al Jabi"
            - name: "Samah AlKasab"
              value: "artist:Samah AlKasab"
      - name: "image"
        field:
          element: "text"
          label: "Grid thumbnail image"
          help: "Filename of uploaded image to appear as grid thumbnail. If no file indicated, will use the first gallery image."
      - name: "gallery"
        field:
          element: multiselect
          label: "Gallery images"
          help: Enter the filenames for uploaded images.
          alterable: true
      - name: "event_date"
        field:
          element: "text"
          label: "Event Date"
          help: "For Exhibition Programming, Event Date"
      - name: "event_location"
        field:
          element: "text"
          label: "Event Location"
          help: "For Exhibition Programming, Event Location (optional)"
      - name: "event_date_ar"
        field:
          element: "text"
          label: "Event Date in Arabic"
          help: "For Exhibition Programming, Event Date in Arabic (optional)"
      - name: "event_location_ar"
        field:
          element: "text"
          label: "Event Location in Arabic"
          help: "For Exhibition Programming, Event Location in Arabic (optional)"
      - name: "event_fb_url"
        field:
          element: "text"
          label: "Facebook Event URL"
          help: "For Exhibition Programming, Event Facebook Page (optional)"
      - name: "published"
        field:
          element: checkbox
          label: "Published"
          help: Check the box when post is ready to be published.
          value: true
